title: "Vansh's Blog"
author: "Vansh Kharidia"
description: "Tech blogs mostly, personal ramblings occasionally." # This will show up in places like Twitter, LinkedIn, etc., if you share your site's URL as a post.

# Email / Social media usernames used by the Minima theme:
# All of these are optional and can be removed or commented out.
email: "vanshkharidia7@gmail.com"
twitter_username: "VanshKharidia"
github_username: "VanshK777"
linkedin_username: "vansh-kharidia"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      tags: "Other"
